// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi5tL4Q-s7as6zII6DHB8G6OC8OPqidRg',
    appId: '1:333931077372:web:2b22167bfb6e69f2ee4179',
    messagingSenderId: '333931077372',
    projectId: 'ba3-business-solutions',
    authDomain: 'ba3-business-solutions.firebaseapp.com',
    storageBucket: 'ba3-business-solutions.appspot.com',
    measurementId: 'G-92W9CD575Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH4wRGk2Huz4qfgkM4SBdsB7qh7Q4V1YQ',
    appId: '1:333931077372:android:47ccc77a5acd4e84ee4179',
    messagingSenderId: '333931077372',
    projectId: 'ba3-business-solutions',
    storageBucket: 'ba3-business-solutions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6aRGMXxIF-NWIW-Fp3q_8vbrpm3Cs_og',
    appId: '1:333931077372:ios:f817acd8f2b14873ee4179',
    messagingSenderId: '333931077372',
    projectId: 'ba3-business-solutions',
    storageBucket: 'ba3-business-solutions.appspot.com',
    iosBundleId: 'com.ba3business.ba3BusinessSolutions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6aRGMXxIF-NWIW-Fp3q_8vbrpm3Cs_og',
    appId: '1:333931077372:ios:d29c55b5e74b5db3ee4179',
    messagingSenderId: '333931077372',
    projectId: 'ba3-business-solutions',
    storageBucket: 'ba3-business-solutions.appspot.com',
    iosBundleId: 'com.ba3business.ba3BusinessSolutions.RunnerTests',
  );
}
